### ISSUE TITLE
Print version information when the program starts

### ISSUE THREAD

**Issue by dxsup** [CloudDectective-Harmonycloud/kindling#112]
**Is your feature request related to a problem? Please describe.**
Whenever an error occurs, we want to know clearly which version of codes the agent is on. But now there is no such information printed by the collector and only an outdated `KINDLING_PROBE_VERSION: v0.1-2021-1221` printed by the probe. We can't know the exact versions of them now. 

**Describe the solution you'd like**
The best version information is the combination of the release version and the commit revision number, IMO. We could insert these numbers as environment variables when we build the containers and print them periodically while the agent is running.

**Additional context**
Any ideas about how we could get this information are appreciated.

**Comment by zjuzzb** [comment]
I find a solution for adding build numbers from git,  take a look at [this](https://pukkaone.github.io/2010/12/19/build-number-git-repository.html).

**Comment by dxsup** [comment]
> I find a solution for adding build numbers from git, take a look at [this](https://pukkaone.github.io/2010/12/19/build-number-git-repository.html).

Looks great! I think it is what we want. We could insert it as a parameter when building the collector, like `go build -ldflags -X main.githash=xxx". Do you have any idea about how we insert it into the probe?

**Comment by zjuzzb** [comment]
> Looks great! I think it is what we want. We could insert it as a parameter when building the collector, like `go build -ldflags -X main.githash=xxx". Do you have any idea about how we insert it into the probe?

```cmake
add_definitions(-DBUILD_NUMBER)
find_package(Git)
if(GIT_FOUND)
    execute_process(
            COMMAND ${GIT_EXECUTABLE} describe --match build
            OUTPUT_VARIABLE BUILD_NUMBER
            OUTPUT_STRIP_TRAILING_WHITESPACE)
    add_definitions(-DBUILD_NUMBER=\ "${BUILD_NUMBER}\")
endif()

```
Add this code into CMakeLists.txt of probe, then just use `BUILD_NUMBER` macro in the source code.

**Comment by dxsup** [comment]
> 
> ```cmake
> add_definitions(-DBUILD_NUMBER)
> find_package(Git)
> if(GIT_FOUND)
>     execute_process(
>             COMMAND ${GIT_EXECUTABLE} describe --match build
>             OUTPUT_VARIABLE BUILD_NUMBER
>             OUTPUT_STRIP_TRAILING_WHITESPACE)
>     add_definitions(-DBUILD_NUMBER=\ "${BUILD_NUMBER}\")
> endif()
> ```
> 
> Add this code into CMakeLists.txt of probe, then just use `BUILD_NUMBER` macro in the source code.

But now we are compiling the probe using Bazel, is there any similar method? @jundizhou

**Comment by sugary199** [comment]
I haven't found a way to inject version information into a program with bazel. Maybe we can generate a header file with a .sh file like this

```shell
commit_ts=`git log -1 --format="%ct"`
commit_time=`date -d@$commit_ts +"%Y-%m-%d %H:%M:%S"`
current_time=`date +"%Y-%m-%d %H:%M:%S"`
git_version=`git log -1 --format="%h"`
build_number=`git describe`
sed  s/MYVERSION/"version: $build_number commit: $commit_time build: $current_time"/g version.h.tmp > version.h
make clean
make
```

There will be a macro in the generated header file

```c
#ifndef _VERSION_
#define _VERSION_ "version: build01-5-g4e4dc12 commit: 2022-03-22 12:57:52 build: 2022-03-22 13:01:26"
#endif
```

Would it work in our project?
