### ISSUE TITLE
the collector start failed caused by "stat ~/.kube/config: no such file or directory"

### ISSUE THREAD

**Issue by yaofighting** [CloudDectective-Harmonycloud/kindling#224]
**Describe the bug**
when I attempt to run the collector at centOS 7.5, I find an error about "stat ~/.kube/config: no such file or directory"
**How to reproduce?**
run the collector process at centOS 7.5

**What did you expect to see?**
the collector should run normally

**What did you see instead?**
the collector didn't run normally with the error infomation "stat ~/.kube/config: no such file or directory"

**Screenshots**
![image](https://user-images.githubusercontent.com/46129108/168530686-93254a29-18be-4aa0-8dc2-6e58e87b2bbd.png)

**What config did you use?**
Config: kindling-collector-config.yml

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx -n kindling -c kindling-probe
kubectl logs -f kindling-agent-xxx -n kindling -c kindling-collector
```
![image](https://user-images.githubusercontent.com/46129108/168532383-ccf750dc-a9ac-458b-aa84-5fbacd5c9783.png)

**Environment (please complete the following information)**
- Kindling agent version
- Kindlinng-falcon-lib version
- Node OS version
- Node Kernel version
- Kubernetes version
- Prometheus version
- Grafana version

**Comment by NeJan2020** [comment]
Closed by #225
