### ISSUE TITLE
document has some language issues

### ISSUE THREAD

**Issue by blue-troy** [CloudDectective-Harmonycloud/kindling#257]
**Describe the bug**
In the document,there is some language issues.something like kindling is splled as `kinndling`,active as `ative`,development as `devlopment`

**Reproduce**
i will not list all the problems

[kindling spell as kinndling](https://github.com/CloudDectective-Harmonycloud/kindling/blame/cfb213c147dcba18360acf35c636d4947a39cf1e/contribute/how_the_core_kindling_team_triage_issues.md#L1)

[active as ative,development as devlopment](https://github.com/CloudDectective-Harmonycloud/kindling/blame/cfb213c147dcba18360acf35c636d4947a39cf1e/README.md#L49)

**Comment by dxsup** [comment]
Closed via #258
