### ISSUE TITLE
 The self-observable exporter to 9501

### ISSUE THREAD

**Issue by crystonesc** [CloudDectective-Harmonycloud/kindling#261]
**Describe the bug**
When i finish install the kindling agent,i found the self-observabel exporter do not work,the 9501 dose not listen on the agent
**How to reproduce?**

**What did you expect to see?**

**What did you see instead?**
A clear and concise description of what you saw instead.

**Screenshots**

**What config did you use?**
Config: (e.g. the yaml config file)

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-probe
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-collector
```
**Environment (please complete the following information)**
- Kindling agent version
- Kindlinng-falcon-lib version
- Node OS version
- Node Kernel version
- Kubernetes version
- Prometheus version
- Grafana version

**Additional context**
Add any other context about the problem here, like appliction protocol.

**Comment by dxsup** [comment]
Yes, the issue exits at version 0.2.0. The port 9501 is not exposed by default while there is a servicemonitor selecting it. We have fixed it by removing the servicemonitor of self-observability exporter by default. 

Please check out the latest yaml.
https://github.com/CloudDectective-Harmonycloud/kindling/blob/cfb213c147dcba18360acf35c636d4947a39cf1e/deploy/agent/kindling-prometheus-servicemonitor.yml

If you need these metrics, you could set the `export_kind` of self-observability exporter to `prometheus` and add the servicemonitor as usual.
https://github.com/CloudDectective-Harmonycloud/kindling/blob/cfb213c147dcba18360acf35c636d4947a39cf1e/deploy/agent/kindling-collector-config.yml#L162-L165
