### ISSUE TITLE
In high QPS scenarios, kindling agent uses too much CPU to transfer event between probe and collector

### ISSUE THREAD

**Issue by jundizhou** [CloudDectective-Harmonycloud/kindling#265]
**Is your feature request related to a problem? Please describe.**
When the single node QPS is greater than 1W, kindling uses more than 1.5 core CPUs, and it is found through the flame diagram that probe and collector use more CPUs for event transmission and serialization

**Describe the solution you'd like**
After my test, I found that if we use CGO, we can avoid the consumption of serialization and deserialization。And the transmission consumption is also slightly reduced

I will add my test cases right away

**Comment by dxsup** [comment]
Closed by #264
