### ISSUE TITLE
Failure to find a BPF probe, try to load kernel probe

### ISSUE THREAD

**Issue by darkfour** [CloudDectective-Harmonycloud/kindling#296]
node环境：
系统 : CentOS 7 
内核版本 : 4.19.236

bug描述：
想使用eBPF模式，eBPF要求内核版本4.14+（满足）。
为何安装时还报错：* Failure to find a BPF probe, try to load kernel probe

**Comment by darkfour** [comment]
> 
你好：
这个看过，这个解决办法（装Linux内核头文件）是走的内核模块吧？没利用到eBPF吧？
看文档：Kindling利用eBPF技术或者内核模块技术构建的探针。
我的疑问是内核版本满足需求的情况下怎样使用到eBPF模式

**Comment by dxsup** [comment]
由于Kindling当前没有实现eBPF代码的CO-RE，所以无论使用内核模块还是eBPF，agent在启动时都需要使用到编译好的产物，我们提前适配了一些常用的内核版本，4.19.236不在适配列表。FAQ中给出的步骤就是在编译**内核模块和eBPF**，编译好后会在agent启动时根据内核版本自动选择使用内核模块还是eBPF，这部分逻辑见文件`collector/docker/kindling-probe-loader`。

**Comment by darkfour** [comment]
> 

明白了，谢谢
