### ISSUE TITLE
kindling probe init err: bpf_load_program()

### ISSUE THREAD

**Issue by darkfour** [CloudDectective-Harmonycloud/kindling#297]
节点环境：
centos7，内核4.19.236

bug描述：
我按照步骤: http://www.kindling.space:33215/project-3/doc-42/
进行预编译，打包成新的镜像了。

kindling-agent一直重启，报错：
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/31338539/180729580-130dfa0d-f7b5-41ff-a235-a2994b87db6f.png">

**Comment by zhuanxuhit** [comment]
strace -febpf 看下具体啥错误

**Comment by jundizhou** [comment]
此问题已在微信群解决，将被关闭

**Comment by jundizhou** [comment]
请根据faq文档操作
