### ISSUE TITLE
Need to improve log format

### ISSUE THREAD

**Issue by NeJan2020** [CloudDectective-Harmonycloud/kindling#298]
There are some problems with our application log.

1. JsonString or detail string should be printed as a message, not a field of `zap.logger`

Now:
https://github.com/CloudDectective-Harmonycloud/kindling/blob/650f8b6cd7c50dd37b69bbad2dfb987668ed0619/collector/pkg/component/receiver/cgoreceiver/cgoreceiver.go#L154-L158

Changed into:
```go
if ce := r.telemetry.Logger.Check(zapcore.DebugLevel, "Receive Event"); ce != nil { 
 	 r.telemetry.Logger.Debug("EventDetail: "+evt.String())
 } 
```
This can prevent JSON strings from being repeatedly escaped.

Output Now:
```text
cgoreceiver/cgoreceiver.go:154  Receive Event   {"event": "{\"Source\":0,\"Timestamp\":1659005015299119841,\"Name\":\"read\",\"Category\":3,\"ParamsNumber\":2,\"UserAttributes\":[{\"Key\":\"res\",\"ValueType\":4,\"Value\":\"agIAAAAAAAA=\"},{\"Key\":\"data\",\"ValueType\":10,\"Value\":\"FwMDAmWXIrg/mjVKH7bWMMBugOXKM4IjDxqDc5VfMnMlMpc+GoKr5swguqQo/EocY8D/6JdXOPttodn6f+wkVEGYCWxmVMK6d1omL7080xo=\"},{\"Key\":\"\",\"ValueType\":0,\"Value\":null},{\"Key\":\"\",\"ValueType\":0,\"Value\":null},{\"Key\":\"\",\"ValueType\":0,\"Value\":null},{\"Key\":\"\",\"ValueType\":0,\"Value\":null},{\"Key\":\"\",\"ValueType\":0,\"Value\":null},{\"Key\":\"\",\"ValueType\":0,\"Value\":null}],\"Ctx\":{\"ThreadInfo\":{\"Pid\":26944,\"Tid\":27216,\"Uid\":0,\"Gid\":0,\"Comm\":\"kube-proxy\",\"ContainerId\":\"b48ce2576573\",\"ContainerName\":\"\"},\"FdInfo\":{\"Num\":16,\"TypeFd\":3,\"Filename\":\"\",\"Directory\":\"\",\"Protocol\":1,\"Role\":false,\"Sip\":[2674330122],\"Dip\":[2086996490],\"Sport\":60808,\"Dport\":6443,\"Source\":0,\"Destination\":0}}}"}
```
Changed into:
```
cgoreceiver/cgoreceiver.go:154  Receive Event   
cgoreceiver/cgoreceiver.go:155  EventDetail: {"Source":0,"Timestamp":1659005015299119841,"Name":"read","Category":3,"ParamsNumber":2,"UserAttributes":[{"Key":"res","ValueType":4,"Value":"agIAAAAAAAA="},{"Key":"data","ValueType":10,"Value":"FwMDAmWXIrg/mjVKH7bWMMBugOXKM4IjDxqDc5VfMnMlMpc+GoKr5swguqQo/EocY8D/6JdXOPttodn6f+wkVEGYCWxmVMK6d1omL7080xo="},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null}],"Ctx":{"ThreadInfo":{"Pid":26944,"Tid":27216,"Uid":0,"Gid":0,"Comm":"kube-proxy","ContainerId":"b48ce2576573","ContainerName":""},"FdInfo":{"Num":16,"TypeFd":3,"Filename":"","Directory":"","Protocol":1,"Role":false,"Sip":[2674330122],"Dip":[2086996490],"Sport":60808,"Dport":6443,"Source":0,"Destination":0}}}
```

2. Using JsonMashal to print obj may be dangerous

https://github.com/CloudDectective-Harmonycloud/kindling/blob/650f8b6cd7c50dd37b69bbad2dfb987668ed0619/collector/pkg/model/kindling_event.go#L239-L242

Since each UserAttributes of KindlingEvent is saved as bytes, it's shown encoded in Base64 now. 
```
{"Key":"data","ValueType":10,"Value":"FwMDAmWXIrg/mjVKH7bWMMBugOXKM4IjDxqDc5VfMnMlMpc+GoKr5swguqQo/EocY8D/6JdXOPttodn6f+wkVEGYCWxmVMK6d1omL7080xo="}
```
This message is useless.
Even if we use `string(attribute)` to convert it, it also contains many invalid characters in the attributes, such as `HTTP/1.1 200 OK\r\n`, which may lead to an error in jsonMarshal.

Another problem is that DataGroup has some private members and would not be printed now.

We should rewrite `MarshalJSON()` for the `KindlingEvent` and `DataGroup` since they are used widely in our program.

**Comment by NeJan2020** [comment]
Another strong requirement is to add a Debug log switch for each component. Many components have very large debug logs. It's better to add additional configuration in telemetry to control it in a selector-like manner.

**Comment by dxsup** [comment]
Good point! Would you like to work on it?

By the way, could this be merged into a single line?

```
cgoreceiver/cgoreceiver.go:154  Receive Event   
cgoreceiver/cgoreceiver.go:155  EventDetail: {"Source":0,"Timestamp":1659005015299119841,"Name":"read","Category":3,"ParamsNumber":2,"UserAttributes":[{"Key":"res","ValueType":4,"Value":"agIAAAAAAAA="},{"Key":"data","ValueType":10,"Value":"FwMDAmWXIrg/mjVKH7bWMMBugOXKM4IjDxqDc5VfMnMlMpc+GoKr5swguqQo/EocY8D/6JdXOPttodn6f+wkVEGYCWxmVMK6d1omL7080xo="},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null}],"Ctx":{"ThreadInfo":{"Pid":26944,"Tid":27216,"Uid":0,"Gid":0,"Comm":"kube-proxy","ContainerId":"b48ce2576573","ContainerName":""},"FdInfo":{"Num":16,"TypeFd":3,"Filename":"","Directory":"","Protocol":1,"Role":false,"Sip":[2674330122],"Dip":[2086996490],"Sport":60808,"Dport":6443,"Source":0,"Destination":0}}}
```

**Comment by NeJan2020** [comment]
> Good point! Would you like to work on it?
> 
> By the way, could this be merged into a single line?
> 
> ```
> cgoreceiver/cgoreceiver.go:154  Receive Event   
> cgoreceiver/cgoreceiver.go:155  EventDetail: {"Source":0,"Timestamp":1659005015299119841,"Name":"read","Category":3,"ParamsNumber":2,"UserAttributes":[{"Key":"res","ValueType":4,"Value":"agIAAAAAAAA="},{"Key":"data","ValueType":10,"Value":"FwMDAmWXIrg/mjVKH7bWMMBugOXKM4IjDxqDc5VfMnMlMpc+GoKr5swguqQo/EocY8D/6JdXOPttodn6f+wkVEGYCWxmVMK6d1omL7080xo="},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null},{"Key":"","ValueType":0,"Value":null}],"Ctx":{"ThreadInfo":{"Pid":26944,"Tid":27216,"Uid":0,"Gid":0,"Comm":"kube-proxy","ContainerId":"b48ce2576573","ContainerName":""},"FdInfo":{"Num":16,"TypeFd":3,"Filename":"","Directory":"","Protocol":1,"Role":false,"Sip":[2674330122],"Dip":[2086996490],"Sport":60808,"Dport":6443,"Source":0,"Destination":0}}}
> ```
Yes, keep the message empty when calling `logger.Check`
```
if ce := r.telemetry.Logger.Check(zapcore.DebugLevel, ""); ce != nil { 
 	 r.telemetry.Logger.Debug("EventDetail: "+evt.String())
 } 
```
