### ISSUE TITLE
kindling init failed to create kprobe 'tcp_drop' error 'No such file or directory'

### ISSUE THREAD

**Issue by QingweiXu** [CloudDectective-Harmonycloud/kindling#313]
Hi,I had a problem when start POD after curl -O https://k8s-bpf-probes-public.oss-cn-hangzhou.aliyuncs.com/kindling-install.tar and sh install.sh,error log as the follow,please double confirm,Thanks!

Ubuntu 20.04 LTS 
Linux ubuntu-master 5.11.5-051105-generic #202103091130 SMP Tue Mar 9 11:51:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**open failed
kindling probe init err: failed to create kprobe 'tcp_drop' error 'No such file or directory'**
sub event name:syscall_exit-writev && category:net
sub event name:syscall_exit-readv && category:net
sub event name:syscall_exit-write && category:net
sub event name:syscall_exit-read && category:net
sub event name:syscall_exit-sendto && category:net
sub event name:syscall_exit-recvfrom && category:net
sub event name:syscall_exit-sendmsg && category:net
sub event name:syscall_exit-recvmsg && category:net
sub event name:kprobe-tcp_close && category:
sub event name:kprobe-tcp_rcv_established && category:
sub event name:kprobe-tcp_drop && category:
sub event name:kprobe-tcp_retransmit_skb && category:
sub event name:syscall_exit-connect && category:
sub event name:kretprobe-tcp_connect && category:
sub event name:kprobe-tcp_set_state && category:
fatal error: unexpected signal during runtime execution

**Comment by jundizhou** [comment]
I look forward to getting more information.
Please execute on node:
cat /sys/kernel/debug/tracing/available_filter_functions ｜grep tcp

**Comment by Kindling-project** [comment]
__ia32_sys_getcpu
__x64_sys_getcpu
bitcpy_rev.constprop.0
bitcpy.constprop.0
htcpld_set_type
htcpld_direction_input
htcpld_unmask
htcpld_mask
htcpld_chip_set_ni
htcpld_register_chip_i2c
htcpld_register_chip_gpio
htcpld_chip_to_irq
htcpld_chip_get
htcpld_setup_chips
htcpld_core_probe
htcpld_chip_set
htcpld_direction_output
htcpld_handler.part.0
htcpld_handler
secure_tcp_seq
secure_tcpv6_ts_off
secure_tcpv6_seq
secure_tcp_ts_off
bpf_tcp_sock
bpf_skc_to_tcp6_sock
bpf_skc_to_tcp_sock
bpf_skc_to_tcp_timewait_sock
bpf_skc_to_tcp_request_sock
bpf_tcp_check_syncookie
bpf_tcp_gen_syncookie
bpf_search_tcp_opt
bpf_xdp_skc_lookup_tcp
bpf_sock_addr_skc_lookup_tcp
bpf_sk_lookup_tcp
bpf_xdp_sk_lookup_tcp
bpf_skc_lookup_tcp
bpf_sock_addr_sk_lookup_tcp
bpf_tcp_sock_is_valid_access
bpf_tcp_sock_convert_ctx_access
flow_rule_match_tcp
__traceiter_tcp_retransmit_skb
__traceiter_tcp_send_reset
__traceiter_tcp_receive_reset
__traceiter_tcp_destroy_sock
__traceiter_tcp_rcv_space_adjust
__traceiter_tcp_retransmit_synack
__traceiter_tcp_probe
tcp_mmap
tcp_get_info_chrono_stats
tcp_init_sock
tcp_splice_data_recv
tcp_sock_set_syncnt
tcp_sock_set_user_timeout
tcp_sock_set_keepintvl
tcp_sock_set_keepcnt
tcp_set_rcvlowat
tcp_zerocopy_vm_insert_batch
tcp_enter_memory_pressure
tcp_leave_memory_pressure
tcp_get_info.part.0
tcp_get_info
__tcp_sock_set_cork.part.0
tcp_sock_set_cork
tcp_get_md5sig_pool
tcp_peek_sndq.constprop.0
__tcp_alloc_md5sig_pool
tcp_alloc_md5sig_pool
tcp_set_state
tcp_recv_timestamp
tcp_inq_hint
tcp_tx_timestamp
tcp_shutdown
tcp_ioctl
tcp_sock_set_nodelay
tcp_peek_len
tcp_zerocopy_set_hint_for_skb.constprop.0
tcp_md5_hash_skb_data
tcp_md5_hash_key
tcp_done
tcp_poll
tcp_recv_skb
tcp_repair_options_est
tcp_push
tcp_send_mss
tcp_remove_empty_skb
tcp_sendmsg_locked
tcp_sendmsg
tcp_build_frag
do_tcp_sendpages
tcp_sendpage_locked
tcp_sendpage
tcp_free_fastopen_req
tcp_cleanup_rbuf
tcp_read_sock
tcp_splice_read
tcp_recvmsg_locked
tcp_recvmsg
tcp_sock_set_quickack
tcp_zerocopy_receive
do_tcp_getsockopt.constprop.0
tcp_getsockopt
tcp_check_oom
__tcp_close
tcp_close
tcp_write_queue_purge
tcp_disconnect
tcp_abort.part.0
tcp_abort
tcp_sock_set_keepidle_locked
tcp_sock_set_keepidle
do_tcp_setsockopt.constprop.0
tcp_setsockopt
tcp_set_window_clamp
tcp_get_timestamping_opt_stats
tcp_enter_quickack_mode
tcp_initialize_rcv_mss
tcp_parse_md5sig_option
tcp_update_pacing_rate
tcp_newly_delivered
tcp_undo_cwnd_reduction
tcp_syn_flood_action
tcp_check_dsack
tcp_parse_mss_option
tcp_measure_rcv_mss
tcp_tso_acked
tcp_match_skb_to_sack
tcp_sndbuf_expand
tcp_init_buffer_space
tcp_reqsk_record_syn
tcp_sacktag_one
tcp_parse_fastopen_option
tcp_parse_options
tcp_collapse_one
tcp_try_coalesce.part.0
tcp_ack_tstamp
tcp_identify_packet_loss
tcp_xmit_recovery
tcp_send_challenge_ack.constprop.0
tcp_sack_compress_send_ack.part.0
tcp_check_urg.isra.0
tcp_urg
tcp_check_sack_reordering
tcp_shifted_skb
tcp_sack_maybe_coalesce
tcp_add_reno_sack.part.0
tcp_try_undo_loss
tcp_ack_update_window.isra.0
__tcp_ack_snd_check
tcp_try_keep_open
tcp_get_syncookie_mss
tcp_enter_cwr
tcp_try_coalesce
tcp_queue_rcv
tcp_collapse
tcp_collapse_ofo_queue
tcp_dsack_extend
tcp_prune_ofo_queue
tcp_process_tlp_ack
tcp_ack_probe
__tcp_ecn_check_ce
tcp_try_undo_recovery
tcp_prune_queue
tcp_try_rmem_schedule
tcp_grow_window
tcp_event_data_recv
tcp_check_space
tcp_send_dupack
tcp_ecn_create_request
tcp_conn_request
tcp_data_queue_ofo
tcp_rtt_estimator
tcp_ack_update_rtt
tcp_clean_rtx_queue
tcp_rcv_space_adjust
tcp_init_cwnd
tcp_mark_skb_lost
tcp_timeout_mark_lost
tcp_simple_retransmit
tcp_mark_head_lost
tcp_skb_shift
tcp_shift_skb_data
tcp_sacktag_walk
tcp_sacktag_write_queue
tcp_clear_retrans
tcp_enter_loss
tcp_cwnd_reduction
tcp_enter_recovery
tcp_fastretrans_alert
tcp_synack_rtt_meas
tcp_rearm_rto
tcp_ack
tcp_rcv_fastopen_synack
tcp_oow_rate_limited
tcp_reset
tcp_validate_incoming
tcp_fin
tcp_ofo_queue
tcp_send_rcvq
tcp_data_ready
tcp_data_queue
tcp_rcv_established
tcp_rbtree_insert
tcp_init_transfer
tcp_finish_connect
tcp_rcv_synsent_state_process
tcp_rcv_state_process
tcp_update_skb_after_send
tcp_init_tso_segs
tcp_connect_queue_skb
tcp_select_initial_window
tcp_fragment_tstamp
tcp_adjust_pcount
tcp_tso_should_defer
tcp_options_write
tcp_established_options
tcp_event_new_data_sent
tcp_synack_options
tcp_syn_options
tcp_cwnd_validate
tcp_wfree
tcp_small_queue_check.isra.0
tcp_rtx_synack.part.0
tcp_rtx_synack
tcp_make_synack
tcp_mss_to_mtu
tcp_ca_dst_init
tcp_schedule_loss_probe.part.0
tcp_mtup_init
tcp_ecn_send_syn
tcp_sync_mss
tcp_connect_init
tcp_mstamp_refresh
tcp_cwnd_restart
tcp_fragment
tcp_trim_head
tcp_mtu_to_mss
tcp_current_mss
tcp_chrono_start
tcp_chrono_stop
tcp_schedule_loss_probe
__tcp_select_window
__tcp_transmit_skb
tcp_send_syn_data
tcp_connect
tcp_xmit_probe_skb
__tcp_send_ack.part.0
__tcp_send_ack
tcp_skb_collapse_tstamp
tcp_mtu_probe
tcp_write_xmit
__tcp_push_pending_frames
tcp_push_one
tcp_collapse_retrans
tcp_retrans_try_collapse
__tcp_retransmit_skb
tcp_send_loss_probe
tcp_retransmit_skb
tcp_xmit_retransmit_queue.part.0
tcp_tsq_write.part.0
tcp_release_cb
tcp_tsq_handler
tcp_tasklet_func
tcp_pace_kick
tcp_xmit_retransmit_queue
tcp_send_fin
tcp_send_active_reset
tcp_send_synack
tcp_send_delayed_ack
tcp_send_ack
tcp_send_window_probe
tcp_write_wakeup
tcp_send_probe0
tcp_syn_ack_timeout
tcp_out_of_resources
tcp_set_keepalive
tcp_compressed_ack_kick
tcp_write_timeout
tcp_keepalive_timer
tcp_clamp_probe0_to_user_timeout
tcp_delack_timer_handler
tcp_delack_timer
tcp_retransmit_timer
tcp_write_timer_handler
tcp_write_timer
tcp_init_xmit_timers
tcp_stream_memory_free
tcp_v4_init_seq
tcp_v4_init_ts_off
tcp_v4_reqsk_destructor
tcp_md5_do_lookup_exact
tcp_v4_restore_cb
tcp_v4_fill_cb
tcp_md5_do_add
tcp_md5_do_del
tcp_v4_md5_hash_headers
tcp_v4_md5_hash_skb
tcp_v4_init_req
tcp_v4_route_req
tcp_filter
tcp4_proc_exit_net
tcp4_proc_init_net
get_tcp4_sock
tcp4_seq_show
tcp_v4_init_sock
tcp_sk_exit_batch
tcp_sk_exit
bpf_iter_fini_tcp
bpf_iter_init_tcp
bpf_iter_tcp_seq_show
tcp_v4_pre_connect
tcp_sk_init.part.0
tcp_sk_init
tcp_ld_RTO_revert.part.0
tcp_ld_RTO_revert
tcp_v4_mtu_reduced.part.0
tcp_v4_mtu_reduced
tcp_v4_parse_md5_keys
tcp_v4_connect
__tcp_md5_do_lookup
tcp_v4_md5_hash_hdr.isra.0
tcp_v4_send_ack
tcp_v4_conn_request
tcp_v4_destroy_sock
tcp_v4_md5_lookup
tcp_v4_send_check
tcp_v4_reqsk_send_ack
tcp_v4_inbound_md5_hash
tcp_twsk_unique
tcp_seek_last_pos
tcp_get_idx
tcp_seq_start
tcp_seq_next
tcp_req_err
tcp_seq_stop
tcp_v4_send_reset
tcp_v4_do_rcv
bpf_iter_tcp_seq_stop
tcp_add_backlog
tcp_v4_syn_recv_sock
tcp_v4_err
__tcp_v4_send_check
tcp_v4_send_synack
tcp_v4_get_syncookie
tcp_v4_early_demux
tcp_v4_rcv
tcp4_proc_exit
tcp_time_wait
tcp_twsk_destructor
tcp_create_openreq_child
tcp_child_process
tcp_check_req
tcp_timewait_state_process
tcp_ca_openreq_child
tcp_openreq_init_rwin
tcp_slow_start
tcp_cong_avoid_ai
tcp_reno_ssthresh
tcp_reno_undo_cwnd
tcp_ca_get_name_by_key
tcp_register_congestion_control
tcp_unregister_congestion_control
tcp_reno_cong_avoid
tcp_ca_find_autoload.constprop.0
tcp_ca_get_key_by_name
tcp_ca_find
tcp_ca_find_key
tcp_assign_congestion_control
tcp_init_congestion_control
tcp_cleanup_congestion_control
tcp_set_default_congestion_control
tcp_get_available_congestion_control
tcp_get_default_congestion_control
tcp_get_allowed_congestion_control
tcp_set_allowed_congestion_control
tcp_set_congestion_control
tcp_metrics_flush_all
tcp_net_metrics_exit_batch
tcp_net_metrics_init.part.0
tcp_net_metrics_init
__tcp_get_metrics
tcp_metrics_nl_cmd_del
tcp_metrics_fill_info
tcp_metrics_nl_dump
tcpm_suck_dst
tcpm_new
__tcp_get_metrics_req
tcp_metrics_nl_cmd_get
tcp_get_metrics
tcp_update_metrics
tcp_init_metrics
tcp_peer_is_proven
tcp_fastopen_cache_get
tcp_fastopen_cache_set
tcp_fastopen_ctx_free
tcp_fastopen_no_cookie
tcp_fastopen_add_skb.part.0
__tcp_fastopen_cookie_gen_cipher.isra.0
tcp_fastopen_cookie_gen_check
tcp_fastopen_create_child
tcp_fastopen_queue_check
tcp_fastopen_destroy_cipher
tcp_fastopen_ctx_destroy
tcp_fastopen_reset_cipher
tcp_fastopen_init_key_once
tcp_fastopen_get_cipher
tcp_fastopen_add_skb
tcp_try_fastopen
tcp_fastopen_cookie_check
tcp_fastopen_defer_connect
tcp_fastopen_active_disable
tcp_fastopen_active_should_disable
tcp_fastopen_active_disable_ofo_check
tcp_fastopen_active_detect_blackhole
tcp_rate_check_app_limited
tcp_rate_skb_sent
tcp_rate_skb_delivered
tcp_rate_gen
tcp_rack_detect_loss
tcp_rack_skb_timeout
tcp_rack_mark_lost
tcp_rack_advance
tcp_rack_reo_timeout
tcp_rack_update_reo_wnd
tcp_newreno_mark_lost
tcp_unregister_ulp
tcp_register_ulp
tcp_get_available_ulp
tcp_update_ulp
tcp_cleanup_ulp
tcp_set_ulp
tcp_gro_complete
tcp4_gro_complete
tcp_gso_segment
tcp4_gso_segment
tcp_gro_receive
tcp4_gro_receive
proc_tcp_fastopen_key
proc_tcp_available_congestion_control
proc_tcp_congestion_control
proc_tcp_available_ulp
proc_tcp_early_demux
snmp_seq_show_tcp_udp.constprop.0.isra.0
tcp_get_cookie_sock
cookie_tcp_reqsk_alloc
bictcp_init
bictcp_recalc_ssthresh
bictcp_acked
bictcp_cong_avoid
bictcp_cwnd_event
bictcp_state
tcp_bpf_stream_read
tcp_bpf_wait_data.constprop.0
tcp_bpf_push
bpf_tcp_ingress.constprop.0
__tcp_bpf_recvmsg
tcp_bpf_sendmsg_redir
tcp_bpf_send_verdict
tcp_bpf_sendmsg
tcp_bpf_sendpage
tcp_bpf_recvmsg
tcp_bpf_get_proto
tcp_bpf_clone
bpf_tcp_ca_check_member
bpf_tcp_send_ack
bpf_tcp_ca_unreg
bpf_tcp_ca_reg
bpf_tcp_ca_init_member
bpf_tcp_ca_init
bpf_tcp_ca_btf_struct_access
bpf_tcp_ca_get_func_proto
bpf_tcp_ca_is_valid_access
espintcp_queue_out
tcp_is_ulp_esp
espintcp_destruct
espintcp_sendskmsg_locked
espintcp_data_ready
espintcp_parse
espintcp_poll
espintcp_close
espintcp_recvmsg
espintcp_rcv
espintcp_push_msgs
espintcp_tx_work
espintcp_sendmsg
espintcp_push_skb
espintcp_release
espintcp_init_sk
espintcp_write_space
tcp_v6_restore_cb
tcp_v6_reqsk_destructor
tcp_v6_fill_cb
tcp_v6_init_ts_off
tcp_v6_init_seq
get_tcp6_sock
tcp6_seq_show
tcp_v6_destroy_sock
tcp_v6_init_sock
tcpv6_net_exit_batch
tcpv6_net_exit
tcpv6_net_init
tcp_v6_mtu_reduced
tcp_v6_early_demux.part.0
tcp_v6_pre_connect
tcp_v6_parse_md5_keys
tcp_v6_md5_hash_headers.isra.0
tcp_v6_md5_hash_skb
tcp_v6_connect
tcp_v6_md5_hash_hdr.isra.0
tcp_v6_send_response
tcp_v6_conn_request
tcp_v6_early_demux
tcp_v6_md5_lookup
tcp_v6_reqsk_send_ack
tcp_v6_inbound_md5_hash
tcp_v6_send_check
tcp_v6_init_req
tcp_v6_route_req
tcp_v6_send_synack
tcp_v6_send_reset
tcp_v6_err
tcp_v6_syn_recv_sock
tcp_v6_do_rcv
tcp_v6_rcv
tcp_v6_get_syncookie
tcp6_proc_init
tcp6_proc_exit
tcpv6_exit
tcp6_gro_complete
tcp6_gso_segment.part.0
tcp6_gro_receive
tcp6_gso_segment
mptcp_sync_mss
mptcp_copy_inaddrs
mptcp_hash
mptcp_unhash
mptcp_listen
mptcp_bind
mptcp_get_port
mptcp_reset_timer
mptcp_sendmsg_frag
__mptcp_recvmsg_mskq
mptcp_try_coalesce
mptcp_rcv_space_adjust
mptcp_getsockopt
mptcp_setsockopt
__mptcp_init_sock
mptcp_enter_memory_pressure
mptcp_close_wake_up.part.0
__mptcp_do_alloc_tx_skb
__mptcp_clear_xmit
__mptcp_update_rmem
mptcp_subflow_get_send
mptcp_push_release
__mptcp_ofo_queue
mptcp_check_data_fin.part.0.isra.0
mptcp_check_data_fin.isra.0
mptcp_stream_connect
mptcp_check_for_eof
__mptcp_alloc_tx_skb
mptcp_alloc_tx_skb
mptcp_poll
mptcp_wait_data
mptcp_check_fastclose
mptcp_tx_cache_refill.constprop.0
__mptcp_wmem_reserve
mptcp_disconnect
mptcp_init_sock.part.0
mptcp_init_sock
__mptcp_clean_una
mptcp_data_queue_ofo
__mptcp_move_skb
__mptcp_move_skbs_from_subflow
mptcp_accept
__mptcp_move_skbs
mptcp_recvmsg
mptcp_stream_accept
__mptcp_flush_join_list
mptcp_schedule_work
mptcp_timeout_timer
mptcp_data_ready
__mptcp_subflow_push_pending
mptcp_retransmit_timer
mptcp_subflow_eof
__mptcp_close_ssk
__mptcp_destroy_sock
mptcp_subflow_shutdown
__mptcp_check_send_data_fin
mptcp_push_pending
mptcp_release_cb
mptcp_sendmsg
__mptcp_wr_shutdown
mptcp_shutdown
mptcp_close
mptcp_worker
mptcp_sk_clone
mptcp_rcv_space_init
mptcp_destroy_common
mptcp_destroy
mptcp_v6_destroy
__mptcp_data_acked
__mptcp_check_push
mptcp_finish_connect
mptcp_finish_join
mptcp_sock_destruct
mptcp_subflow_discard_data
mptcp_subflow_init_cookie_req
mptcp_subflow_reset
mptcp_subflow_fully_established
mptcp_subflow_data_available
mptcp_space
mptcpv6_handle_mapped
mptcp_subflow_create_socket
__mptcp_subflow_connect
mptcp_parse_option
mptcp_established_options_add_addr
mptcp_established_options_mp.constprop.0
mptcp_established_options_dss.constprop.0
mptcp_get_options
mptcp_syn_options
mptcp_established_options
mptcp_synack_options
mptcp_update_rcv_data_fin
mptcp_incoming_options
mptcp_write_options
mptcp_token_iter_next
mptcp_token_get_sock
mptcp_token_new_request
mptcp_token_new_connect
mptcp_token_accept
mptcp_token_exists
mptcp_token_destroy_request
mptcp_token_destroy
mptcp_crypto_key_sha
mptcp_crypto_hmac_sha
mptcp_net_init
mptcp_net_exit
mptcp_is_enabled
mptcp_get_add_addr_timeout
mptcp_pm_schedule_work
mptcp_pm_announce_addr
mptcp_pm_remove_addr
mptcp_pm_remove_subflow
mptcp_pm_new_connection
mptcp_pm_allow_new_subflow
mptcp_pm_fully_established
mptcp_pm_connection_closed
mptcp_pm_subflow_established
mptcp_pm_subflow_closed
mptcp_pm_add_addr_received
mptcp_pm_add_addr_send_ack
mptcp_pm_rm_addr_received
mptcp_pm_add_addr_signal
mptcp_pm_rm_addr_signal
mptcp_pm_get_local_id
mptcp_pm_data_init
mptcp_diag_subflow_init
mptcp_mib_alloc
mptcp_seq_show
mptcp_nl_fill_addr
mptcp_pm_parse_addr
mptcp_nl_cmd_get_addr
mptcp_pm_add_timer
mptcp_nl_cmd_dump_addrs
mptcp_nl_cmd_set_limits
mptcp_nl_cmd_get_limits
mptcp_pm_alloc_anno_list
mptcp_pm_nl_append_new_local_addr
mptcp_nl_cmd_add_addr
mptcp_pm_del_add_timer
mptcp_nl_remove_subflow_and_signal_addr.isra.0
mptcp_nl_cmd_del_addr
mptcp_nl_cmd_flush_addrs
mptcp_pm_free_anno_list
mptcp_pm_nl_add_addr_send_ack
mptcp_pm_create_subflow_or_signal_addr
mptcp_pm_nl_fully_established
mptcp_pm_nl_subflow_established
mptcp_pm_nl_add_addr_received
mptcp_pm_nl_rm_addr_received
mptcp_pm_nl_rm_subflow_received
mptcp_pm_nl_get_local_id
mptcp_pm_nl_data_init
mptcp_token_join_cookie_init_state
bitcpy_rev.constprop.0 [syscopyarea]
bitcpy.constprop.0 [syscopyarea]
nf_ct_tcp_fixup [nf_conntrack]
tcp_can_early_drop [nf_conntrack]
tcp_timeout_nlattr_to_obj [nf_conntrack]
tcp_timeout_obj_to_nlattr [nf_conntrack]
tcp_nlattr_tuple_size [nf_conntrack]
tcp_to_nlattr [nf_conntrack]
nlattr_to_tcp [nf_conntrack]
tcp_options [nf_conntrack]
tcp_sack [nf_conntrack]
tcp_in_window [nf_conntrack]
tcp_new [nf_conntrack]
nf_conntrack_tcp_packet [nf_conntrack]
nf_conntrack_tcp_init_net [nf_conntrack]
nf_ct_tcp_seqadj_set [nf_conntrack]
tcp_error_log [nf_conntrack]
__nf_nat_mangle_tcp_packet [nf_nat]
tcp_mt_check [xt_tcpudp]
udp_mt_check [xt_tcpudp]
tcp_mt [xt_tcpudp]
udp_mt [xt_tcpudp]
nft_payload_offload_tcp.constprop.0.isra.0 [nf_tables]
get_tcpmss [nf_tables]
nft_exthdr_tcp_set_init [nf_tables]
nft_tcp_header_pointer.part.0.constprop.0 [nf_tables]
nft_exthdr_tcp_eval [nf_tables]
nft_exthdr_tcp_set_eval [nf_tables]
ip_vs_tcpudp_debug_packet_v4 [ip_vs]
ip_vs_tcpudp_debug_packet_v6 [ip_vs]
ip_vs_tcpudp_debug_packet [ip_vs]
tcp_state_name [ip_vs]
tcp_timeout_change [ip_vs]
tcp_unregister_app [ip_vs]
tcp_register_app [ip_vs]
tcp_app_conn_bind [ip_vs]
__ip_vs_tcp_exit [ip_vs]
__ip_vs_tcp_init [ip_vs]
tcp_csum_check.constprop.0 [ip_vs]
tcp_state_transition [ip_vs]
tcp_conn_schedule [ip_vs]
tcp_dnat_handler [ip_vs]
tcp_snat_handler [ip_vs]
ip_vs_tcp_conn_listen [ip_vs]
nf_reject_ip_tcphdr_get [nf_reject_ipv4]
nf_reject_ip_tcphdr_put [nf_reject_ipv4]
nf_reject_skb_v4_tcp_reset [nf_reject_ipv4]

**Comment by QingweiXu** [comment]
The more info:

[tcp.txt](https://github.com/CloudDectective-Harmonycloud/kindling/files/9565042/tcp.txt)

**Comment by jundizhou** [comment]
Please use package to solve this problem temporarily. We will solve this problem in next version
[new-build.tar.zip](https://github.com/CloudDectective-Harmonycloud/kindling/files/9565341/new-build.tar.zip)

![image](https://user-images.githubusercontent.com/92794317/190127021-d2eebbf9-85fd-4e80-8115-966cadcf0487.png)

You can refer to the content of faq：1. I only modified the script
http://www.kindling.space:33215/project-1/doc-35/

**Comment by jundizhou** [comment]
Resolved in #320
