### ISSUE TITLE
network analyzer 调用ReadBytes 时 slice out of bound bug

### ISSUE THREAD

**Issue by LambertZhaglog** [CloudDectective-Harmonycloud/kindling#326]
**Describe the bug**
[ReadBytes](https://github.com/CloudDectective-Harmonycloud/kindling/blob/main/collector/pkg/component/analyzer/network/protocol/protocol_parser.go#L138) 当输入参数len 是负值，函数体内maxLength 也是负值时，出现 slice out of bound 
**How to reproduce?**
Steps to reproduce the behavior.

**What did you expect to see?**

**What did you see instead?**
A clear and concise description of what you saw instead.

**Screenshots**

**What config did you use?**
Config: (e.g. the yaml config file)

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-probe
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-collector
```
**Environment (please complete the following information)**
- Kindling agent version
- Kindlinng-falcon-lib version
- Node OS version
- Node Kernel version
- Kubernetes version
- Prometheus version
- Grafana version

**Additional context**
Add any other context about the problem here, like appliction protocol.

**Comment by dxsup** [comment]
请问是在什么情况下遇到了len是负数的情况？请求的协议是什么？

**Comment by LambertZhaglog** [comment]
我认为这个错误是函数实现的错误，和协议无关。场景是这样的，给kindling开发解析公司自研协议的解析器，图方便，调用了作为库的readbytes，然而协议序列化并不是按网络字节序的，读4字节数据作为len为负值

**Comment by hocktea214** [comment]
ReadBytes()没有参数非法验证，此处修改返回类型，添加error

**Comment by hocktea214** [comment]
```
ReadBytes(offset int, length int) (toOffset int, value []byte, err error)
```
使用时 需进行error非空判断

```
offset, data, err := message.ReadBytes(offset, length)
if err != nil {
	return
}
```
