### ISSUE TITLE
kindlingproject/agent-builder go build -o 时，build 碰到warning 不输出可执行文件

### ISSUE THREAD

**Issue by LambertZhaglog** [CloudDectective-Harmonycloud/kindling#329]
**Describe the bug**
我在基于kindling进行二次开发，使用deploy/scripts/run_docker.sh 进行编译。编译的过程中提示我某个变量declare but not used，我认为这只是个warning，不影响编译结果。但事实不是这样的。我发现我无论对代码进行怎样的更改，编译后程序的行为不变（比如我在代码中添加printf 语句，但编译后程序print nothing）。 

我花费了两天的时间才搞清楚问题的原因

我之前成功的（没有任何warning）编译得到了kindling-collector 可执行文件。之后所有对代码的更改因为warning 没能生成新的可执行文件覆盖kindling-collector。但因为old kindling-collector文件的存在，[ 这里](https://github.com/CloudDectective-Harmonycloud/kindling/blob/main/deploy/scripts/build.sh#L16) 判断后，总是不报错，正常完成镜像构建

严格来说这不是个bug，但这个feature 很容易浪费更多人的“两天时间”

**What did you expect to see?**
有warning 就不要成功构建出镜像了

**Comment by dxsup** [comment]
感谢反馈，确实应该退出。最简单的修改方法是每次执行`go build`前先清理之前的产物，这里我们优化一下。

**Comment by dxsup** [comment]
请问你已经修复过这部分了吗，如果已经修复了可以提交Pull Reqeust

**Comment by dxsup** [comment]
你好，这个问题已经在https://github.com/CloudDectective-Harmonycloud/kindling/pull/330中解决
