### ISSUE TITLE
Can't receive events after the probe is restarted

### ISSUE THREAD

**Issue by dxsup** [CloudDectective-Harmonycloud/kindling#34]
**Describe the bug**
Can't receive events after the probe is restarted.
**What you expected to happen**
The collector is supposed to receive events from the probe.
**How to reproduce**
Start kindling and restart the probe, then you will see the collector can't receive any events.
**Additional context**
The collector starts to receive events after sending the subscribing events. The root cause of this bug is that after the probe is restarted, it loses information about subscribing in which case it won't send events.
Therefore, to fix this bug, the feature that the collector can resend the subscribing events is requested.

**Comment by jundizhou** [comment]
I need to investigate the reconnection mechanism of zeromq

There are three situations:

First, the probe is restarted, but the collector is alive

Second, the probe is alive, but the collector restarts

Third, probe and collector are all restarted

Maybe zeromq can support disconnection detection, and maybe we need to do process detection ourselves

**Comment by dxsup** [comment]
#51 temporarily avoids the happening of this issue, though the solution doesn't really solve it. I'll retain this issue open to tracking a more complete solution.

**Comment by dxsup** [comment]
This issue is invalid after merging #264 because there is only one container now.
