### ISSUE TITLE
kindling probe init err: bpf_load_program() err=13

### ISSUE THREAD

**Issue by Dingzhen1233** [CloudDectective-Harmonycloud/kindling#356]
### Discussed in https://github.com/CloudDectective-Harmonycloud/kindling/discussions/355

<div type='discussions-op-text'>

<sup>Originally posted by **Dingzhen1233** November 16, 2022</sup>
系统：Ubuntu 18.04.2 LTS

1、初始化部署时因为Error: Precompiled module at /opt/.kindling/ is not found，按照FAQ中的内容重新打了kindling-agent的镜像
2、部署之后pod持续报错重启：

3204: (71) r3 = *(u8 *)(r9 +6)
 R0=inv0 R1=inv(id=0) R2=inv(id=0) R3=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4=inv(id=0) R6=map_value(id=0,off=0,ks=4,vs=240,imm=0) R7=map_value(id=0,off=0,ks=4,vs=240,imm=0) R8=inv(id=0) R9=map_value(id=0,off=0,ks=4,vs=397,imm=0) R10=fp0 fp-280=map_value fp-296=ctx fp-304=map_value
3205: (71) r6 = *(u8 *)(r9 +7)
 R0=inv0 R1=inv(id=0) R2=inv(id=0) R3=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4=inv(id=0) R6=map_value(id=0,off=0,ks=4,vs=240,imm=0) R7=map_value(id=0,off=0,ks=4,vs=240,imm=0) R8=inv(id=0) R9=map_value(id=0,off=0,ks=4,vs=397,imm=0) R10=fp0 fp-280=map_value fp-296=ctx fp-304=map_value
3206: (67) r6 <<= 8
3207: (4f) r6 |= r3
3208: (67) r6 <<= 16
3209: (4f) r6 |= r2
3210: (67) r6 <<= 32
3211: (4f) r6 |= r1
3212: (85) call bpf_ktime_get_ns#5
3213: (0f) r0 += r6
3214: (7b) *(u64 *)(r7 +16) = r0
 R0=inv(id=0) R6=inv(id=0) R7=map_value(id=0,off=0,ks=4,vs=240,imm=0) R8=inv(id=0) R9=map_value(id=0,off=0,ks=4,vs=397,imm=0) R10=fp0 fp-280=map_value fp-296=ctx fp-304=map_value
3215: (bf) r2 = r10
3216: (07) r2 += -8
3217: (18) r1 = 0xffffa0a658ab8c00
3219: (bf) r3 = r7
3220: (b7) r4 = 0
3221: (85) call bpf_map_update_elem#2
R3 type=map_value expected=fp
kindling probe init err: bpf_load_program() err=13 event=finish_task_switch message=0: (bf) r8 = r1
1: (b7) r1 = 0
2: (63) *(u32 *)(r10 -248) = r1
3: (bf) r2 = r10
4: (07) r2 += -248
5: (18) r1 = 0xffffa0b67bf1e000
7: (85) call bpf_map_lookup_elem#1
8: (bf) r9 = r0
9: (15) if r9 2022/11/16 12:30:14 Failed to run application: failed to start application: fail to init probe

**Comment by jundizhou** [comment]
look at https://github.com/CloudDectective-Harmonycloud/kindling/discussions/355
