### ISSUE TITLE
Error happened when compiling eBPF modules on kernel 4.19.24-9.al7.x86_64

### ISSUE THREAD

**Issue by dxsup** [CloudDectective-Harmonycloud/kindling#79]
**Describe the bug**
Error happened when compiling eBPF modules on the kernel of 4.19.24-9.al7.x86_64. 

**How to reproduce?**
Just compile the agent-libs repository following the instructions at [Installation](https://github.com/Kindling-project/kindling/blob/main/installation/Installation.md) on the kernel version of 4.19.24-9.al7.x86_64. This kernel could be downloaded at [Aliyun Mirrors](https://mirrors.aliyun.com/alinux/2/plus/x86_64/Packages/).

**What did you expect to see?**
No errors happened.

**What did you see instead?**
Several errors happened and no eBPF product was compiled. But the kernel module is OK.

**Screenshots**
<img width="712" alt="image" src="https://user-images.githubusercontent.com/46807570/156695633-38930ef3-cd5f-4a32-9b30-53804cb9328d.png">

**Environment (please complete the following information)**
- Kindlinng-falcon-lib version: Based on the latest codes on the branch of kindling-dev. The commit is 8c130f7c4326398372661c0148b5bba5a1a2e9d8.
- Node Kernel version: 4.19.24-9.al7.x86_64

**Comment by jundizhou** [comment]
In some alibaba cloud kernel versions, the loginuid field does not exist If your analysis code does not use this field, you can delete this field when using kindling, or use the kernel module .We will not delete this field in the release version of kindling

**Comment by zjuzzb** [comment]
> In some alibaba cloud kernel versions, the loginuid field does not exist If your analysis code does not use this field, you can delete this field when using kindling, or use the kernel module .We will not delete this field in the release version of kindling

Maybe we can add a macro about the kernel version to control the loginuid field. In my view, it's not appropriate for users to modify the code themselves.

**Comment by jundizhou** [comment]
> > In some alibaba cloud kernel versions, the loginuid field does not exist If your analysis code does not use this field, you can delete this field when using kindling, or use the kernel module .We will not delete this field in the release version of kindling
> 
> Maybe we can add a macro about the kernel version to control the loginuid field. In my view, it's not appropriate for users to modify the code themselves.

I think this adaptation is endless, because this field does exist in the main branch of Linux, which is deleted by the distribution. We can adapt to CentOS, Ubuntu and other mainstream operating systems, but not at the expense of functionality

**Comment by zjuzzb** [comment]
> I think this adaptation is endless, because this field does exist in the main branch of Linux, which is deleted by the distribution. We can adapt to CentOS, Ubuntu and other mainstream operating systems, but not at the expense of functionality

![1646903523508_11F180F7-9567-4077-85CD-2C4EA82CD38E](https://user-images.githubusercontent.com/34501766/157629334-ff93562f-2b2a-4b1a-958e-8d18cedf29f5.png)

This field of task_struct is controlled by a kernel compiling option, so it may be a common problem. At least we can give a patch about how to remove this field, which can make users easier to solve the problem.

**Comment by dxsup** [comment]
Then I'm wondering why the original repository of [agent-libs](https://github.com/draios/agent-libs) doesn't provide such macro. Are they requiring this kernel compiling option?

**Comment by jundizhou** [comment]
> > I think this adaptation is endless, because this field does exist in the main branch of Linux, which is deleted by the distribution. We can adapt to CentOS, Ubuntu and other mainstream operating systems, but not at the expense of functionality
> 
> ![1646903523508_11F180F7-9567-4077-85CD-2C4EA82CD38E](https://user-images.githubusercontent.com/34501766/157629334-ff93562f-2b2a-4b1a-958e-8d18cedf29f5.png)
> 
> This field of task_struct is controlled by a kernel compiling option, so it may be a common problem. At least we can give a patch about how to remove this field, which can make users easier to solve the problem.

As you can see, how can we solve this problems. This seems to be beyond the control of the code

**Comment by J-lena** [comment]
Now that it exists in the Linux's distribution history, shouldn't  Kindling be compatible with those distributions that may still be used?
